[pytest]
minversion = 7.0

# Ignore ./config (which contains the configure-time check_pytest.py tests) by
# default.
addopts = --ignore ./config

# Common test code can be found here.
pythonpath = src/test/pytest
